# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_bg', models.ImageField(blank=True, upload_to='homepage/', verbose_name='Hero BG Image')),
                ('about_title', models.CharField(blank=True, max_length=200, verbose_name='About Section Title')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
        ),
    ]
