# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('logo', models.ImageField(blank=True, help_text='Preferably a transparent PNG.', upload_to='companies/')),
                ('info', models.TextField(blank=True, help_text='Brief description of company.', max_length=350)),
                ('link', models.CharField(blank=True, help_text="Optional link to company's site.", max_length=150)),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('my_order',),
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
