# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('date_of_contact', models.DateTimeField(auto_now=True, verbose_name='Date of Initial Contact')),
                ('contacted', models.BooleanField(default=False, verbose_name='Contacted?')),
            ],
            options={
                'ordering': ('date_of_contact',),
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
            },
        ),
    ]
