# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 19:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-date_of_contact',), 'verbose_name': 'Contact Request', 'verbose_name_plural': 'Contact Requests'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_copy',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About Section Copy'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='About Image'),
        ),
    ]
