# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 19:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170801_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mission_copy',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mission Section Copy'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_title',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Mission Section Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='spacer_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Spacer Image #1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='spacer_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Spacer Image #2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='spacer_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Spacer Image #3'),
        ),
    ]
