# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_homepage_spacer_image_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='companies_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Companies Section Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Team Section Title'),
        ),
    ]
