# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170801_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='companies_title',
            field=models.CharField(blank=True, default='Our Companies', max_length=150, null=True, verbose_name='Companies Section Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='team_title',
            field=models.CharField(blank=True, default='Our Team', max_length=150, null=True, verbose_name='Team Section Title'),
        ),
    ]
