# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 16:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170807_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Brief bio of employee.', max_length=350),
        ),
    ]
