# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 02:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170822_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('logo', models.ImageField(blank=True, help_text='Preferably a transparent PNG. This logo will be layered on top of the white hero background.', upload_to='company_pages/')),
                ('text_block', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text block')),
                ('pullquote', models.TextField(blank=True, null=True, verbose_name='Text block pullquote (optional)')),
                ('pullquote_source', models.CharField(blank=True, max_length=150, verbose_name='Text block pullquote source')),
                ('image', models.ImageField(blank=True, upload_to='company_pages/', verbose_name='Text block image (optional)')),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('my_order',),
                'verbose_name': 'Company Page',
                'verbose_name_plural': 'Company Pages',
            },
        ),
    ]
