# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_companypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypage',
            name='short_description',
            field=models.TextField(blank=True, help_text='This will show on the homepage for this company.', null=True, verbose_name='Short description of company'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='companies_selector',
            field=models.ManyToManyField(blank=True, to='main.CompanyPage'),
        ),
    ]
