# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180702_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypage',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='companies_selector',
            field=models.ManyToManyField(blank=True, help_text='Select the companies you want to show on the homepage.', to='main.CompanyPage', verbose_name='Company selector'),
        ),
    ]
