# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 21:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180702_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='pullquote',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='pullquote_source',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='text_block',
        ),
        migrations.AddField(
            model_name='companypage',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='company_pages/', verbose_name='Image (optional)'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='company_pages/', verbose_name='Image (optional)'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='pullquote_1',
            field=models.TextField(blank=True, null=True, verbose_name='Pullquote (optional)'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='pullquote_1_source',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pullquote source (optional)'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='pullquote_2',
            field=models.TextField(blank=True, null=True, verbose_name='Pullquote (optional)'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='pullquote_2_source',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pullquote source (optional)'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='text_block_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='text_block_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='companypage',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(blank=True, max_length=150), max_length=150, null=True),
        ),
    ]
