# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180703_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypage',
            name='show_company_name',
            field=models.BooleanField(default=True),
        ),
    ]
