# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 23:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_companypage_show_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypage',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='company_pages/', verbose_name='Image (optional)'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='pullquote_3',
            field=models.TextField(blank=True, null=True, verbose_name='Pullquote (optional)'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='pullquote_3_source',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pullquote source (optional)'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='show_block_1',
            field=models.BooleanField(default=True, verbose_name='Show Block #1 Content'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='show_block_2',
            field=models.BooleanField(default=True, verbose_name='Show Block #2 Content'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='show_block_3',
            field=models.BooleanField(default=True, verbose_name='Show Block #3 Content'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='text_block_3',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
