# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180703_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='companies_selector',
            new_name='companies',
        ),
    ]
