# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-08 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_companypage_external_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypage',
            name='hero_bg',
            field=models.ImageField(blank=True, help_text="If you don't upload a background image, the background will default to white.", null=True, upload_to='company_pages/', verbose_name='Background Hero Image'),
        ),
        migrations.AlterField(
            model_name='companypage',
            name='show_block_2',
            field=models.BooleanField(default=False, verbose_name='Show Block #2 Content'),
        ),
        migrations.AlterField(
            model_name='companypage',
            name='show_block_3',
            field=models.BooleanField(default=False, verbose_name='Show Block #3 Content'),
        ),
    ]
