# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-11 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180707_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='detail_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CompanyPage'),
        ),
        migrations.AlterField(
            model_name='company',
            name='link',
            field=models.CharField(blank=True, help_text="Optional external link to company's site.", max_length=150),
        ),
    ]
