# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-11 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180711_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='detail_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CompanyPage'),
        ),
    ]
