# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-11 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20180711_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='detail_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='main.CompanyPage'),
        ),
    ]
