# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180711_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypage',
            name='full_width_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='company_pages/', verbose_name='Full Width Image'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='full_width_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='company_pages/', verbose_name='Full Width Image'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='full_width_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='company_pages/', verbose_name='Full Width Image'),
        ),
    ]
